### ISSUE TITLE
libssh2 1.8 on Archlinux

### ISSUE THREAD

**Issue by psamim** [uglide/qredisclient#18]
Hi,
I have libssh 1.8 installed on my machine, I get the following error:

```error: static assertion failed: QRedisClient requires libss2 >= 1.6.0
 static_assert((LIBSSH2_VERSION_MAJOR == 1) && (LIBSSH2_VERSION_MINOR >= 6), "QRedisClient requires libss2 >= 1.6.0");
 ^~~~~~~~~~~~~```

**Comment by uglide** [comment]
@psamim  Are you sure that you have correct library in include path?

**Comment by psamim** [comment]
@uglide I have libssh library at `/usr/include`, what is the correct way to add it to include path?

**Comment by jonjomckay** [comment]
This is also happening to me on Arch Linux - I have libssh 1.8.0 installed and on the default path (I've been able to compile in the past)

**Comment by cotko** [comment]
@jonjomckay 
I'm on arch too, for some reason I had libssh2.h in `/usr/local/include` path which apparently was used while building. I've checked pacman to see if any packages were using it and there were none, so I just removed those files `rm /usr/local/include/libssh2*`

**Comment by uglide** [comment]
Looks like @cotko suggestion resolves this issue.
