### ISSUE TITLE
So bad

### ISSUE THREAD

**Issue by erm3nda** [uglide/qredisclient#4]
Don't start... but hey!!! it started GoogleMP and also auto-sent the error reporting without showing info to mee :V

I don't choose opensource to let the software do what you want. Error reporting should be manual or at least ask user. That is a "medium-big" reason to leave using that software.

Take that as a sincerly report.

**Comment by uglide** [comment]
Are you crazy? :) qredisclient is just c++ library to communicate with Redis. And it doesn't contain any "GoogleMP" and "auto-sent" error reporting.

**Comment by erm3nda** [comment]
Totally agree with you. That issue was from the RedisDesktopManager. The url displayed in the error box didn't allow me to copy the proper url and I really didn't pay attention at exact name of repo. Sorry.
