### ISSUE TITLE
is this api support redis-cluster？

### ISSUE THREAD

**Issue by ff20082171** [uglide/qredisclient#48]

**Comment by uglide** [comment]
yes, it is

**Comment by ff20082171** [comment]
> yes, it is

Thank you for your reply, but I tested the cluster mode of redis-3.2 on windows. The six port numbers of the cluster are 6380，6381，6382，6383，6384，6385.I write to port 6380, when I write data, it will return a reconnect to 6381. After that, I will not write data. Can you provide an example under the cluster? Thank you again
