### ISSUE TITLE
Strict type checking

### ISSUE THREAD

**Issue by jgwinner** [uglide/qredisclient#51]
I'm getting errors due to C type loose type checking:

```
   responseparser.cpp(80) : error C2440 : 'initializing' : cannot convert from 'void *(__cdecl *)(const redisReadTask *,int)' to 'void *(__cdecl *)(const redisReadTask *,size_t)'
   responseparser.cpp(80) : note: None of the functions with this name in scope match the target type
   responseparser.cpp(80) : error C2440 : 'initializing' : cannot convert from 'void *(__cdecl *)(const redisReadTask *)' to 'void *(__cdecl *)(const redisReadTask *,double,char *,size_t)'
   responseparser.cpp(80) : note: None of the functions with this name in scope match the target type
   responseparser.cpp(80) : error C2440 : 'initializing' : cannot convert from 'void (__cdecl *)(void *)' to 'void *(__cdecl *)(const redisReadTask *)'


```

Here's an example page that describes the problem:

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2440?view=vs-2019

and

https://docs.microsoft.com/en-us/cpp/build/reference/zc-strictstrings-disable-string-literal-type-conversion?view=vs-2019

Any chance this can be fixed?

Also, is this 32 bit / 64 bit compatible? The above errors also said something about int to size_t, so I wasn't sure if it's 32/64 compatible.

Unfortunately, the .pro files aren't completely useful to us, as we've inherited a project that used both WxWidgets and QT5, and the .pro files aren't being used (it's not a QT app, but there's plenty of QT code); as a result I have to admit I just sort of threw your code into the source build and got the above errors. Interestingly, the VC project doesn't explicitly set it, but it looks like Qt did (in file `Qt\mkspecs\common\msvc-version.conf` )

        == John ==

**Comment by uglide** [comment]
You need to apply https://github.com/uglide/qredisclient/blob/master/3rdparty/hiredis-win.patch to compile client on Windows.
